language: java
script:
    - mvn verify -P withPitest


# travis before "script" runs:
#     mvn install -DskipTests=true -B
# and this invokes pitest, because it doesn't follow 'skipTests', like surefire and filesafe.
# So we have to put pitest in custom profile, because we don't want to execute pitest before standard tests.
# After that we have to call 'verify' with profile that contain pitest execution.
# Pitest in our pom is attached to 'verify' phase.