language: java
script:
    - mvn verify

# travis before "script" runs:    mvn install -DskipTests=true -B
# and default runs:   mvn test
# but we have pitest attached to 'verify' phase, and it is in profile activated when there is no 'skipTests'.
# So everything works ok, pitest is executed after normal tests.