language: java
sudo: false
jdk:
    - oraclejdk9
    - oraclejdk8
    - openjdk8
before_install:
    - chmod -R 777 script/*.sh
script:
    - ./script/ci-test.sh
after_success:
    - ./script/ci-coverage.sh
